### ISSUE TITLE
Color in preview layout

### ISSUE THREAD

**Issue by Zoltar358** [joplin/plugin-abc-sheet-music#1]
Thank you, it is a fantastic plugin.

There is one thing that could be useful for me.
Right now, preview is rendered in black. I'm using dark theme in Joplin, so it's almost invisible.
Can you adjust this plugin to match theme colors? Or at least add lighter color to choose from?
I am not a programmer, so for me, it's very hard to figure out how to do that and build this plugin from source.

Thank you very much.

**Comment by laurent22** [comment]
Yes I'm planning to fix this by forcing a white background behind the notes. A black background with white notes would be tricky to implement I think, and might look a bit odd too.

**Comment by Zoltar358** [comment]
That's great news. Thank you for your response.
