### ISSUE TITLE
search alters abc plugin render

### ISSUE THREAD

**Issue by jjon** [joplin/plugin-abc-sheet-music#5]
I don't know if this qualifies as a bug, but it certainly must be unintended behavior:
Searching on a string removes the searched string from the rendered `abc` codeblock:
Searching for the string "ADorian" finds both occurrences in the `abc` codeblock and the `python` codeblock, but it removes the string from the rendered `abc`.

These two codeblocks render as expected:
![image](https://user-images.githubusercontent.com/279479/229601748-b6fdd570-84fc-4da4-bab3-27ba7cd23429.png)
But, searching for the string "ADorian" alters the render of the `abc`:
![image](https://user-images.githubusercontent.com/279479/229601794-f837b2ec-ad69-4a27-aa53-d127803f0787.png)

**Comment by laurent22** [comment]
Thanks for the report. This is actually an issue with the app, and it's now fixed in https://github.com/laurent22/joplin/commit/0c8de68b8058969a00e49ac10258666c7d084aea
