### ISSUE TITLE
Android and LilyPond Support

### ISSUE THREAD

**Issue by JaneX8** [joplin/plugin-abc-sheet-music#6]
This is great. I think Joplin for Android does not support plugins (yet) but then this functionality should be a default part of the Android app just like other additional support that can be enabled in the Android app.

Adding LilyPond support to this plugin as for example requested here (https://discourse.joplinapp.org/t/music-notation/3978) would be a great addition, considering that the rendering of music notes is already available in this plugin. I'm not sure but it could be as simple as converting LilyPond to ABC notation and then passing that data in already existing functions.

**Comment by laurent22** [comment]
That would be nice, but unfortunately LilyPond seems quite special and difficult to parse. It would need an executable file that we can't really bundle with the app or a plugin

**Comment by JaneX8** [comment]
@laurent22 is there a way to get support for ABC notation in the Android app?

**Comment by laurent22** [comment]
Not currently but we're trying to make it work. Hopefully we'll support plugins on mobile too, which would make this work

**Comment by JaneX8** [comment]
That'd be great. 👌🏻 Thank you.

**Comment by laurent22** [comment]
The ABC plugin is now working in the latest development version of the mobile app!

https://discourse.joplinapp.org/t/mobile-plugin-support/35262

![image](https://github.com/joplin/plugin-abc-sheet-music/assets/1285584/32664782-cb14-4209-992b-80c0ff81fff6)

Which means it should be part of the official app within the next few months

**Comment by laurent22** [comment]
Version 3.0 of the mobile app is out and now supports plugins including the ABC one!
