### ISSUE TITLE
Unable to install plugin - "Please upgrade Joplin"

### ISSUE THREAD

**Issue by clarkras** [joplin/plugin-abc-sheet-music#8]
Joplin is blocking me from installing the plugin - it says, "Please upgrade Joplin to use this plugin", but when I checked for Joplin updates, it says that I'm up to date.

![image](https://github.com/joplin/plugin-abc-sheet-music/assets/2540950/43766560-596f-4ee7-9fc1-8f16d6cd9cee)

**Comment by rrblocker** [comment]
Same problem here.

**Comment by laurent22** [comment]
Hello, sorry about that, the next Joplin version is going to be available within the next few days
