### ISSUE TITLE
Export as PDF File dosn't work

### ISSUE THREAD

**Issue by dna-johnny** [joplin/plugin-abc-sheet-music#9]
I tried to export the rendered notation as pdf and I get this message:
![2024-02-02 12_21_59-Joplin](https://github.com/joplin/plugin-abc-sheet-music/assets/26166606/e5a94fa1-6a75-42b7-8c52-1c3b9def53da)

There are no html file in this folder.

**Comment by laurent22** [comment]
There was an issue on both the plugin and application. The issue is fixed on both now but you'll need to wait till the next 3.0 release before you can try again. If you need this now, you can download the next pre-release which should be available soon

**Comment by dna-johnny** [comment]
Works for me with 3.0.3
Thanks
